/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClaseGratisRouteImport } from './routes/clase-gratis'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as CreadorRouteImport } from './routes/creador'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated/cuenta'
import { Route as AuthenticatedCursoRouteImport } from './routes/_authenticated/curso'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminContenidoRouteImport } from './routes/_authenticated/admin/contenido'
import { Route as AuthenticatedAdminPaginaRouteImport } from './routes/_authenticated/admin/pagina'
import { Route as AuthenticatedAdminPagosRouteImport } from './routes/_authenticated/admin/pagos'
import { Route as AuthenticatedAdminPreciosRouteImport } from './routes/_authenticated/admin/precios'
import { Route as AuthenticatedAdminTutorRouteImport } from './routes/_authenticated/admin/tutor'
import { Route as AuthenticatedLeccionLessonIdRouteImport } from './routes/_authenticated/leccion.$lessonId'
import { Route as AuthenticatedTestQuizIdRouteImport } from './routes/_authenticated/test.$quizId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaseGratisRoute = ClaseGratisRouteImport.update({
  id: '/clase-gratis',
  path: '/clase-gratis',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const CreadorRoute = CreadorRouteImport.update({
  id: '/creador',
  path: '/creador',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoRoute = AuthenticatedCursoRouteImport.update({
  id: '/curso',
  path: '/curso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminContenidoRoute =
  AuthenticatedAdminContenidoRouteImport.update({
    id: '/contenido',
    path: '/contenido',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaginaRoute =
  AuthenticatedAdminPaginaRouteImport.update({
    id: '/pagina',
    path: '/pagina',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagosRoute = AuthenticatedAdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPreciosRoute =
  AuthenticatedAdminPreciosRouteImport.update({
    id: '/precios',
    path: '/precios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTutorRoute = AuthenticatedAdminTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedLeccionLessonIdRoute =
  AuthenticatedLeccionLessonIdRouteImport.update({
    id: '/leccion/$lessonId',
    path: '/leccion/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestQuizIdRoute = AuthenticatedTestQuizIdRouteImport.update({
  id: '/test/$quizId',
  path: '/test/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clase-gratis': typeof ClaseGratisRoute
  '/comprar': typeof ComprarRoute
  '/creador': typeof CreadorRoute
  '/gracias': typeof GraciasRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/curso': typeof AuthenticatedCursoRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/pagina': typeof AuthenticatedAdminPaginaRoute
  '/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/admin/precios': typeof AuthenticatedAdminPreciosRoute
  '/admin/tutor': typeof AuthenticatedAdminTutorRoute
  '/leccion/$lessonId': typeof AuthenticatedLeccionLessonIdRoute
  '/test/$quizId': typeof AuthenticatedTestQuizIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clase-gratis': typeof ClaseGratisRoute
  '/comprar': typeof ComprarRoute
  '/creador': typeof CreadorRoute
  '/gracias': typeof GraciasRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/curso': typeof AuthenticatedCursoRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/pagina': typeof AuthenticatedAdminPaginaRoute
  '/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/admin/precios': typeof AuthenticatedAdminPreciosRoute
  '/admin/tutor': typeof AuthenticatedAdminTutorRoute
  '/leccion/$lessonId': typeof AuthenticatedLeccionLessonIdRoute
  '/test/$quizId': typeof AuthenticatedTestQuizIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/clase-gratis': typeof ClaseGratisRoute
  '/comprar': typeof ComprarRoute
  '/creador': typeof CreadorRoute
  '/gracias': typeof GraciasRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/_authenticated/curso': typeof AuthenticatedCursoRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/_authenticated/admin/pagina': typeof AuthenticatedAdminPaginaRoute
  '/_authenticated/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/_authenticated/admin/precios': typeof AuthenticatedAdminPreciosRoute
  '/_authenticated/admin/tutor': typeof AuthenticatedAdminTutorRoute
  '/_authenticated/leccion/$lessonId': typeof AuthenticatedLeccionLessonIdRoute
  '/_authenticated/test/$quizId': typeof AuthenticatedTestQuizIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clase-gratis'
    | '/comprar'
    | '/creador'
    | '/gracias'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cuenta'
    | '/curso'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/contenido'
    | '/admin/pagina'
    | '/admin/pagos'
    | '/admin/precios'
    | '/admin/tutor'
    | '/leccion/$lessonId'
    | '/test/$quizId'
    | '/admin/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clase-gratis'
    | '/comprar'
    | '/creador'
    | '/gracias'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cuenta'
    | '/curso'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/contenido'
    | '/admin/pagina'
    | '/admin/pagos'
    | '/admin/precios'
    | '/admin/tutor'
    | '/leccion/$lessonId'
    | '/test/$quizId'
    | '/admin'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/clase-gratis'
    | '/comprar'
    | '/creador'
    | '/gracias'
    | '/mcp'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/cuenta'
    | '/_authenticated/curso'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/contenido'
    | '/_authenticated/admin/pagina'
    | '/_authenticated/admin/pagos'
    | '/_authenticated/admin/precios'
    | '/_authenticated/admin/tutor'
    | '/_authenticated/leccion/$lessonId'
    | '/_authenticated/test/$quizId'
    | '/_authenticated/admin/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClaseGratisRoute: typeof ClaseGratisRoute
  ComprarRoute: typeof ComprarRoute
  CreadorRoute: typeof CreadorRoute
  GraciasRoute: typeof GraciasRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clase-gratis': {
      id: '/clase-gratis'
      path: '/clase-gratis'
      fullPath: '/clase-gratis'
      preLoaderRoute: typeof ClaseGratisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creador': {
      id: '/creador'
      path: '/creador'
      fullPath: '/creador'
      preLoaderRoute: typeof CreadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso': {
      id: '/_authenticated/curso'
      path: '/curso'
      fullPath: '/curso'
      preLoaderRoute: typeof AuthenticatedCursoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/contenido': {
      id: '/_authenticated/admin/contenido'
      path: '/contenido'
      fullPath: '/admin/contenido'
      preLoaderRoute: typeof AuthenticatedAdminContenidoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pagina': {
      id: '/_authenticated/admin/pagina'
      path: '/pagina'
      fullPath: '/admin/pagina'
      preLoaderRoute: typeof AuthenticatedAdminPaginaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pagos': {
      id: '/_authenticated/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AuthenticatedAdminPagosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/precios': {
      id: '/_authenticated/admin/precios'
      path: '/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AuthenticatedAdminPreciosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tutor': {
      id: '/_authenticated/admin/tutor'
      path: '/tutor'
      fullPath: '/admin/tutor'
      preLoaderRoute: typeof AuthenticatedAdminTutorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/leccion/$lessonId': {
      id: '/_authenticated/leccion/$lessonId'
      path: '/leccion/$lessonId'
      fullPath: '/leccion/$lessonId'
      preLoaderRoute: typeof AuthenticatedLeccionLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test/$quizId': {
      id: '/_authenticated/test/$quizId'
      path: '/test/$quizId'
      fullPath: '/test/$quizId'
      preLoaderRoute: typeof AuthenticatedTestQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminContenidoRoute: typeof AuthenticatedAdminContenidoRoute
  AuthenticatedAdminPaginaRoute: typeof AuthenticatedAdminPaginaRoute
  AuthenticatedAdminPagosRoute: typeof AuthenticatedAdminPagosRoute
  AuthenticatedAdminPreciosRoute: typeof AuthenticatedAdminPreciosRoute
  AuthenticatedAdminTutorRoute: typeof AuthenticatedAdminTutorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminContenidoRoute: AuthenticatedAdminContenidoRoute,
    AuthenticatedAdminPaginaRoute: AuthenticatedAdminPaginaRoute,
    AuthenticatedAdminPagosRoute: AuthenticatedAdminPagosRoute,
    AuthenticatedAdminPreciosRoute: AuthenticatedAdminPreciosRoute,
    AuthenticatedAdminTutorRoute: AuthenticatedAdminTutorRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
  AuthenticatedCursoRoute: typeof AuthenticatedCursoRoute
  AuthenticatedLeccionLessonIdRoute: typeof AuthenticatedLeccionLessonIdRoute
  AuthenticatedTestQuizIdRoute: typeof AuthenticatedTestQuizIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
  AuthenticatedCursoRoute: AuthenticatedCursoRoute,
  AuthenticatedLeccionLessonIdRoute: AuthenticatedLeccionLessonIdRoute,
  AuthenticatedTestQuizIdRoute: AuthenticatedTestQuizIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClaseGratisRoute: ClaseGratisRoute,
  ComprarRoute: ComprarRoute,
  CreadorRoute: CreadorRoute,
  GraciasRoute: GraciasRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
